- hosts: all
  become: yes
  tasks:
   - name: Install http
     yum:
       name: httpd
       state: started
       
    # Start HTTP Services   
   - name: Start HTTPD
     systemd:
       name: httpd
       state: started
