---
- hosts: all
  become: yes
  tasks:
   # This is to Install and configure HTTP
   - name: Install http
     yum:
       name: httpd
       state: started
       
   - name: Start HTTPD
     systemd:
       name: httpd
       state: started
